#!/bin/sh
set -eu

PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

if [ "$#" -gt 0 ]; then
  input="$*"
else
  input="$(cat)"
fi

if [ -z "$input" ]; then
  echo "No input text" >&2
  exit 1
fi

shortcut_cache="$HOME/.cache/shortcuts"
/bin/mkdir -p "$shortcut_cache"

input_file="$(mktemp "${TMPDIR:-/tmp}/make-spoken-audio-track.XXXXXX")"
marker_file="$(mktemp "${TMPDIR:-/tmp}/make-spoken-audio-track-marker.XXXXXX")"
trap '/bin/rm -f "$input_file" "$marker_file"' EXIT
printf "%s" "$input" >"$input_file"

result="$(/usr/bin/osascript - "$input_file" <<'APPLESCRIPT'
on run argv
  set inputPath to item 1 of argv
  set inputText to do shell script "/bin/cat " & quoted form of inputPath
  tell application "Shortcuts Events"
    return run shortcut "Make Spoken Audio Track" with input inputText
  end tell
end run
APPLESCRIPT
)"

if [ "$result" != "SUCCESS" ]; then
  echo "Shortcut returned: $result" >&2
  exit 1
fi

audio_path="$(
  /usr/bin/find "$shortcut_cache" -type f -newer "$marker_file" \
    \( -iname '*.caf' -o -iname '*.m4a' -o -iname '*.aiff' -o -iname '*.mp3' -o -iname '*.wav' \) \
    -print0 |
    /usr/bin/xargs -0 /usr/bin/stat -f '%m %N' |
    /usr/bin/sort -nr |
    /usr/bin/head -n 1 |
    /usr/bin/sed 's/^[0-9][0-9]* //'
)"

if [ -z "$audio_path" ]; then
  echo "Shortcut succeeded but no audio file was found in $shortcut_cache" >&2
  exit 1
fi

extension="${audio_path##*.}"
renamed_path="$shortcut_cache/spoken-audio-$(/bin/date +%Y%m%d-%H%M%S)-$$.$extension"
/bin/mv "$audio_path" "$renamed_path"

printf "%s\n" "$renamed_path"
