#!/bin/sh
set -eu

PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

if [ "$#" -gt 0 ]; then
  summary="$(/Users/rioredwards/scripts/process-text-for-speech "$*")"
else
  summary="$(cat | /Users/rioredwards/scripts/process-text-for-speech)"
fi

/Users/rioredwards/scripts/make-spoken-audio-track "$summary"
