#!/bin/sh
set -eu

process_text="$HOME/scripts/sc-helpers/process-text-for-speech"

if [ "$#" -gt 0 ]; then
  summary="$("$process_text" "$*")"
else
  summary="$(cat | "$process_text")"
fi

printf "%s" "$summary" | /usr/bin/pbcopy
"$HOME/scripts/sc" speak-clipboard-raw
printf "%s\n" "$summary"
