#!/bin/sh
set -eu

process_text="$HOME/scripts/sc-helpers/process-text-for-speech"
make_spoken_audio_path="$HOME/scripts/sc-helpers/make-spoken-audio-path"

if [ "$#" -gt 0 ]; then
  summary="$("$process_text" "$*")"
else
  summary="$(cat | "$process_text")"
fi

printf "%s" "$summary" | "$make_spoken_audio_path"
